# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

# ====================================
# Spring PROPERTIES
# ====================================

spring:
  application:
    name: locale-services-api

  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        default_schema: "locale"
        format_sql: true
        dialect: com.cresen.locale.config.CustomDialectConfig
        temp.use_jdbc_metadata_defaults: false
        order_inserts: true
        order_updates: true
        jdbc:
          lob.non_contextual_creation: true
          batch_size: 20
          fetch_size: 20
          batch_versioned_data: true

# ====================================

# ====================================
# LOGGING PROPERTIES
# ====================================
logging:
  level:
    jdbc:
      sqlonly: info
      resultsettable: info
      sqltiming: fatal
      audit: fatal
      resultset: fatal
      connection: info

    org:
      springframework.orm.jpa: ERROR
      hibernate.jdbc: ERROR

    com.zaxxer.hikari.HikariConfig: ERROR


---

spring:
  profiles: local
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hcpcontracting_dev
    #    url: "jdbc:postgresql://10.0.3.5:5432/hcp_contracting_dev?stringtype=unspecified&sslmode=require"
    username: postgres
    #    username: cresen@cresenpgsqldev
    #    password: Monitor1234#
    password: superuser

server:
  port: 9009

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
  instance:
    preferIpAddress: true

---

spring:
  profiles: prod

---

spring:
  profiles: dev

---

