
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hcpcontracting_dev
    #    url: "jdbc:postgresql://10.0.3.5:5432/hcp_contracting_dev?stringtype=unspecified&sslmode=require"
    username: postgres
    #    username: cresen@cresenpgsqldev
    #    password: Monitor1234#
    password: superuser

server:
  port: 9009

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
  instance:
    preferIpAddress: true